import "./globals.css";
import type { Metadata, Viewport } from "next";
import { Inter } from "next/font/google";
import { ThemeProvider } from "@/contexts/ThemeContext";
import AuthProvider from "@/contexts/AuthContext";
import AppProvider from "@/contexts/AppContext";
import ChatProvider from "@/contexts/ChatContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    manifest: "/manifest.json",
    title: "Prompt Engineers Chat",
    description: "Generated by create next app",
};

export const viewport: Viewport = {
    themeColor: "#000",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <head>
                <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.9.0/styles/github-dark-dimmed.css"></link>
            </head>
            <body className={inter.className}>
                <ThemeProvider>
                    <AppProvider>
                        <AuthProvider>
                            <ChatProvider>{children}</ChatProvider>
                        </AuthProvider>
                    </AppProvider>
                </ThemeProvider>
            </body>
        </html>
    );
}
