stages:
  - test

variables:
  OPENAI_API_KEY: ${OPENAI_API_KEY}
  BUCKET: pe-oss-bucket
  S3_REGION: us-east-1
  ACCESS_KEY_ID: ${ACCESS_KEY_ID}
  ACCESS_SECRET_KEY: ${ACCESS_SECRET_KEY}
  PYTHONPATH: "${CI_PROJECT_DIR}/backend/src:${CI_PROJECT_DIR}/backend"  

cache:
  paths:
    - .cache/pip

test:
  stage: test
  image: python:3.10
  variables:
    APP_ENV: test
    APP_SECRET: this-is-a-test-secret
  before_script:
    - python --version
    - pip install --upgrade pip
    - env | sort
  script:
    - cd backend
    - mkdir -p data
    - pip install uv
    - uv pip install -v --system --no-cache-dir -c constraints.txt -r requirements.txt -r requirements-dev.txt
    - pytest -rs
  # only:
  #   changes:
  #     - backend/**/*
