stages:
  - test
  - build

variables:
  BUCKET: pe-oss-bucket
  S3_REGION: us-east-1
  PYTHONPATH: "${CI_PROJECT_DIR}/backend/src:${CI_PROJECT_DIR}/backend"  

cache:
  paths:
    - .cache/pip

# test:
#   stage: test
#   image: python:3.10
#   variables:
#     APP_ENV: test
#     APP_SECRET: this-is-a-test-secret
#   before_script:
#     - python --version
#     - pip install --upgrade pip
#     - env | sort
#   script:
#     - cd backend
#     - mkdir -p data
#     - pip install uv
#     - uv pip install -v --system --no-cache-dir -c constraints.txt -r requirements.txt -r requirements-dev.txt
#     - pytest -rs
#   # only:
#   #   changes:
#   #     - backend/**/*
#   except:
#     - tags

build:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_JOB_TOKEN" "$CI_REGISTRY"
  script:
    - cd backend
    - docker build -t "$CI_REGISTRY_IMAGE:latest" .
    - docker push "$CI_REGISTRY_IMAGE:latest"
  only:
    - development
    - master