stages:
  - test

variables:
  APP_ENV: development
  APP_SECRET: this-is-a-test-secret
  OPENAI_API_KEY: $OPENAI_API_KEY
  BUCKET: pe-oss-bucket
  S3_REGION: us-east-1
  ACCESS_KEY_ID: $ACCESS_KEY_ID
  ACCESS_SECRET_KEY: $ACCESS_SECRET_KEY

cache:
  paths:
    - .cache/pip

test:
  stage: test
  image: python:3.10
  before_script:
    - python --version
    - pip install --upgrade pip
  script:
    - mkdir -p data
    - cd backend
    - pip install uv
    - uv pip install -v --system --no-cache-dir -c constraints.txt -r requirements.txt -r requirements-dev.txt
    - pytest -rs
  only:
    changes:
      - backend/**/*
