"""create-tools-and-headers-table

Revision ID: 07d4856c3f84
Revises: c4f899f92a3f
Create Date: 2024-08-08 19:28:41.489951

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from src.config import database_type


# revision identifiers, used by Alembic.
revision: str = '07d4856c3f84'
down_revision: Union[str, None] = 'c4f899f92a3f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tools',
        sa.Column('id', sa.String(36), primary_key=True),
        sa.Column('name', sa.String(100), nullable=False),
        sa.Column('description', sa.TEXT(), nullable=False),
        sa.Column('link', sa.String(255), nullable=True),
        sa.Column('toolkit', sa.String(30), nullable=False, default='API'),
        sa.Column('url', sa.String(255), nullable=False),
        sa.Column('method', sa.String(7), nullable=False, default='GET'),
        sa.Column('args', sa.JSON(), nullable=True),
        sa.Column('user_id', sa.String(36), nullable=False),
        sa.Column('created_at', database_type('DATE'), nullable=False),
        sa.Column('updated_at', database_type('DATE'), nullable=False),
        sa.UniqueConstraint('name', 'user_id', name='uq_tools_name_user_id')
    )
    op.create_index('ix_tools_user_id', 'tools', ['user_id'])
    
    op.create_table('headers',
        sa.Column('id', sa.String(36), primary_key=True),
        sa.Column('key', sa.String(255), nullable=False),
        sa.Column('value', sa.TEXT(), nullable=False),
        sa.Column('encrypted', sa.Boolean(), nullable=False, default=False),
        sa.Column('tool_id', sa.String(36), nullable=False),
        sa.Column('created_at', database_type('DATE'), nullable=False),
        sa.Column('updated_at', database_type('DATE'), nullable=False),
        sa.UniqueConstraint('key', 'tool_id', name='uq_headers_key_tool_id'),
        sa.ForeignKeyConstraint(['tool_id'], ['tools.id'], ondelete='CASCADE'),
    )
    op.create_index('ix_headers_tool_id', 'headers', ['tool_id'])


def downgrade() -> None:
    ## Drop headers
    op.drop_index('ix_headers_tool_id', table_name='headers')
    op.drop_table('headers')
    
    ## Drop tools
    op.drop_index('ix_tools_user_id', table_name='tools')
    op.drop_table('tools')
    
